name: helloworld
description: Hello World Conference Official App.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_staggered_animations: ^0.1.2
  animated_background: ^1.0.5
  rflutter_alert: ^1.0.3
  connectivity: ^0.4.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  assets:
    - assets/icon.png
    - assets/logotipo.png
    - assets/question-circle.png
    - assets/calendar-edit-1.png
    - assets/headphones-customer-support-human.png
    - assets/location-user.png
    - assets/megaphone-1.png
    - assets/binocular.png
    - assets/tags-favorite-star.png
    - assets/bookmarks-document.png
    - assets/logout-2.png
    - assets/login-2.png
    - assets/developer-community-github-1.png
    - assets/social-media-facebook-1.png
    - assets/fail.png
    - assets/flash-off.png
    - assets/remove-badge.png
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Light.ttf
  uses-material-design: true

